#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SOURCE_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
INSTALL_ROOT="/opt/patch-manager/agent-linux"
SERVICE_NAME="patch-manager-agent-linux.service"
SERVICE_TARGET="/etc/systemd/system/${SERVICE_NAME}"
ENV_TARGET="/etc/patch-manager/agent-linux.env"
API_URL=""
SERVER_URL=""
AGENT_ID=""
EXECUTION_MODE="dry-run"
LOG_FILE="/var/log/patch-manager/agent-linux.log"
BOOTSTRAP_TOKEN=""

usage() {
  cat <<'EOF'
Usage:
  ./deploy/install-linux-agent-guided.sh [options]

Options:
  --server URL           Patch Manager server URL (example: http://10.0.0.15:8000)
  --api-url URL          Full agent API URL (overrides --server)
  --bootstrap-token TOK  Bootstrap token used for first enrollment
  --agent-id ID          Optional agent identifier (auto-generated by default)
  --mode MODE            Agent fallback mode: dry-run or apply
  --install-root PATH    Target install path (default: /opt/patch-manager/agent-linux)
  --log-file PATH        Agent log file path
  --help                 Show this message

Example:
  ./deploy/install-linux-agent-guided.sh \
    --server http://10.0.0.15:8000 \
    --bootstrap-token bootstrap-token-value
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --server)
      SERVER_URL="${2:-}"
      shift 2
      ;;
    --api-url)
      API_URL="${2:-}"
      shift 2
      ;;
    --bootstrap-token)
      BOOTSTRAP_TOKEN="${2:-}"
      shift 2
      ;;
    --agent-id)
      AGENT_ID="${2:-}"
      shift 2
      ;;
    --mode)
      EXECUTION_MODE="${2:-}"
      shift 2
      ;;
    --install-root)
      INSTALL_ROOT="${2:-}"
      shift 2
      ;;
    --log-file)
      LOG_FILE="${2:-}"
      shift 2
      ;;
    --help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1"
      usage
      exit 1
      ;;
  esac
done

if [[ -n "${SERVER_URL}" && -z "${API_URL}" ]]; then
  API_URL="${SERVER_URL%/}/api/v1/agents"
fi

if [[ -z "${API_URL}" ]]; then
  echo "Error: --server or --api-url is required."
  usage
  exit 1
fi

if [[ -z "${BOOTSTRAP_TOKEN}" ]]; then
  echo "Error: --bootstrap-token is required."
  usage
  exit 1
fi

if [[ "${EXECUTION_MODE}" != "dry-run" && "${EXECUTION_MODE}" != "apply" ]]; then
  echo "Error: --mode must be dry-run or apply."
  exit 1
fi

if ! command -v python3 >/dev/null 2>&1; then
  echo "Error: python3 not found."
  exit 1
fi

if ! command -v rsync >/dev/null 2>&1; then
  echo "Error: rsync not found."
  exit 1
fi

if [[ -z "${AGENT_ID}" ]]; then
  HOSTNAME_VALUE="$(hostname -s 2>/dev/null || hostname)"
  AGENT_ID="linux-$(echo "${HOSTNAME_VALUE}" | tr '[:upper:]' '[:lower:]' | tr -cs 'a-z0-9' '-')"
  AGENT_ID="${AGENT_ID%-}"
fi

sudo mkdir -p "${INSTALL_ROOT}"
sudo mkdir -p /etc/patch-manager
sudo mkdir -p /var/log/patch-manager

sudo rsync -a --delete "${SOURCE_ROOT}/" "${INSTALL_ROOT}/"

if ! id patchmanager >/dev/null 2>&1; then
  sudo useradd --system --create-home --shell /usr/sbin/nologin patchmanager
fi

sudo tee "${ENV_TARGET}" >/dev/null <<EOF
PATCH_MANAGER_API=${API_URL}
PATCH_MANAGER_AGENT_KEY=
PATCH_MANAGER_AGENT_ID=${AGENT_ID}
PATCH_MANAGER_BOOTSTRAP_TOKEN=${BOOTSTRAP_TOKEN}
PATCH_MANAGER_AGENT_VERSION=0.2.0
PATCH_MANAGER_EXECUTION_MODE=${EXECUTION_MODE}
PATCH_MANAGER_ENABLE_REAL_APPLY=false
PATCH_MANAGER_ALLOW_SECURITY_ONLY=false
PATCH_MANAGER_ALLOWED_PACKAGE_PATTERNS=
PATCH_MANAGER_APT_APPLY_TIMEOUT=900
PATCH_MANAGER_HEARTBEAT_INTERVAL=10
PATCH_MANAGER_IDLE_SLEEP=5
PATCH_MANAGER_INVENTORY_INTERVAL=60
PATCH_MANAGER_FAILURE_BACKOFF=10
PATCH_MANAGER_REQUEST_TIMEOUT=10
PATCH_MANAGER_LOG_LEVEL=INFO
PATCH_MANAGER_LOG_TO_STDOUT=true
PATCH_MANAGER_LOG_FILE=${LOG_FILE}
EOF
sudo chown root:patchmanager "${ENV_TARGET}"
sudo chmod 660 "${ENV_TARGET}"

sudo install -m 644 "${INSTALL_ROOT}/deploy/${SERVICE_NAME}" "${SERVICE_TARGET}"
sudo chown -R patchmanager:patchmanager "${INSTALL_ROOT}" /var/log/patch-manager
sudo systemctl daemon-reload

echo "Instalacao concluida."
echo "Arquivo de ambiente gerado em ${ENV_TARGET}."
echo "Agent ID detectado: ${AGENT_ID}"
echo "Comandos sugeridos:"
echo "  sudo systemctl enable --now ${SERVICE_NAME}"
echo "  sudo systemctl status ${SERVICE_NAME}"
echo "  sudo journalctl -u ${SERVICE_NAME} -f"
